//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebappClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/top10words", ReplyAction="http://tempuri.org/IService1/top10wordsResponse")]
        string top10words(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/top10words", ReplyAction="http://tempuri.org/IService1/top10wordsResponse")]
        System.Threading.Tasks.Task<string> top10wordsAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/top10wordscontent", ReplyAction="http://tempuri.org/IService1/top10wordscontentResponse")]
        string top10wordscontent(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/top10wordscontent", ReplyAction="http://tempuri.org/IService1/top10wordscontentResponse")]
        System.Threading.Tasks.Task<string> top10wordscontentAsync(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebappClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebappClient.ServiceReference1.IService1>, WebappClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string top10words(string url) {
            return base.Channel.top10words(url);
        }
        
        public System.Threading.Tasks.Task<string> top10wordsAsync(string url) {
            return base.Channel.top10wordsAsync(url);
        }
        
        public string top10wordscontent(string url) {
            return base.Channel.top10wordscontent(url);
        }
        
        public System.Threading.Tasks.Task<string> top10wordscontentAsync(string url) {
            return base.Channel.top10wordscontentAsync(url);
        }
    }
}
